### ISSUE TITLE
cabal --seed throws error

### ISSUE THREAD

**Issue by okdistribute** [cabal-club/cabal-cli#178] opened 2020-04-24 18:57 UTC
On 11.2.0, after `rm -rf ~/.cabal`

```
$ npm install -g cabal
$ cabal cabal.chat --seed
Seeding cabal.chat

@: new peer
x: peer left
^: uploaded a chunk
.: downloaded a chunk


TypeError: Cannot read property 'ready' of undefined
    at trackAndPrintEvents (/home/okdistribute/.nvm/versions/node/v12.4.0/lib/node_modules/cabal/cli.js:332:9)
    at /home/okdistribute/.nvm/versions/node/v12.4.0/lib/node_modules/cabal/cli.js:322:9
    at Array.forEach (<anonymous>)
    at /home/okdistribute/.nvm/versions/node/v12.4.0/lib/node_modules/cabal/cli.js:314:12
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

Are there automated tests for cabal for the `--seed` command?

**Comment by noffle** [comment] 2020-04-24 20:16
Is this on the latest version (11.2.0)?

**Comment by rinchen** [comment] 2020-05-01 22:19
I can get this to fail on multiple versions of nodejs but not in the manner reported. Still present in Cabal 11.2.0

1. Launch Cabal and join the public chat
2. Navigate to the status channel
3. Type "/add abcd"

**Comment by rinchen** [comment] 2020-05-06 04:24
So I don't hijack this thread, I'll open up a different bug report

**Comment by noffle** [comment] 2020-06-20 02:03
Confirmed still crashing on 13.1.6.

**Comment by noffle** [comment] 2020-06-20 02:16
Fixed on the main branch. It will be included in the next CLI release. The problem was trying to look up the cabal in cabal-client using the DNS name instead of the actual resolved key.

**Closed by noffle** 2020-06-20 02:16 UTC
